name: CI/CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Install NPM Packages
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm install

      - name: Cache Composer Packages
        uses: actions/cache@v3
        id: cache-vendor
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer Packages
        if: ${{ steps.cache-vendor.outputs.cache-hit != 'true' }}
        uses: php-actions/composer@v6

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node Modules Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Use Vendor Cache
        uses: actions/cache@v3
        with:
          path: '**/vendor'
          key: ${{ runner.os }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Run Unit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          args: tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy in EC2
        env:
            RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY  }}
            EC2_SSH_USERNAME : ${{ secrets.EC2_SSH_USERNAME  }}
            EC2_SSH_PUBLIC_IP_ADDRESS : ${{ secrets.EC2_SSH_PUBLIC_IP_ADDRESS  }}
        run: |
          echo "$RSA_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${EC2_SSH_USERNAME}@${EC2_SSH_PUBLIC_IP_ADDRESS} '
            echo && \
          
            echo "**Command: navigating to directory cd /var/www/html --------------------" &&
            cd /var/www/html && echo -e "\n" &&

            echo "**Command: checkout main -----------------------------------------------" &&
            sudo git checkout main && echo -e "\n" &&

            echo "**Command: git fetch ---------------------------------------------------" &&
            sudo git fetch --all && echo -e "\n" &&

            echo "**Command: git reset ---------------------------------------------------" &&
            sudo git reset --hard origin/main && echo -e "\n" &&
            
            echo "**Command: git pull ----------------------------------------------------" &&
            sudo git pull origin main && echo -e "\n" &&
            
            echo "**Command: npm install --omit=dev --------------------------------------" &&
            sudo npm install --omit=dev && echo -e "\n" &&
            
            echo "**Command: composer install -o --no-dev --------------------------------" &&
            sudo composer install -o --no-dev
          '